spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_handmade_dev
spring.datasource.username=postgres
spring.datasource.password=123456

# Hi?n câu l?nh SQL rõ ràng
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hi?n giá tr? c?a các tham s? truy?n vào câu SQL (?? xem email, password g?i lên là gì)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Hi?n l?i chi ti?t c?a Spring Security (?? bi?t t?i sao b? 401/403)
logging.level.org.springframework.security=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect